services:
  - type: web
    name: mark-lab
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn crmproject.wsgi --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
